# Use the official Go image
FROM golang:1.23

WORKDIR /app

# Install Air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum first
COPY go.* ./
RUN go mod download

# Copy the rest of the source code
COPY . .

# Expose API port
EXPOSE 8080

# Run air for hot reload
CMD ["air"]